/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.tinkoff.bpm.pledge.submission.registration.process;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CreateSubmissionEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5902663416288981722L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CreateSubmissionEvent\",\"namespace\":\"ru.tinkoff.bpm.pledge.submission.registration.process\",\"fields\":[{\"name\":\"applicationIntegrationId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"submissionType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CreateSubmissionEvent> ENCODER =
      new BinaryMessageEncoder<CreateSubmissionEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CreateSubmissionEvent> DECODER =
      new BinaryMessageDecoder<CreateSubmissionEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CreateSubmissionEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CreateSubmissionEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CreateSubmissionEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CreateSubmissionEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CreateSubmissionEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CreateSubmissionEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CreateSubmissionEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CreateSubmissionEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String applicationIntegrationId;
  @Deprecated public java.lang.String submissionType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CreateSubmissionEvent() {}

  /**
   * All-args constructor.
   * @param applicationIntegrationId The new value for applicationIntegrationId
   * @param submissionType The new value for submissionType
   */
  public CreateSubmissionEvent(java.lang.String applicationIntegrationId, java.lang.String submissionType) {
    this.applicationIntegrationId = applicationIntegrationId;
    this.submissionType = submissionType;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return applicationIntegrationId;
    case 1: return submissionType;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: applicationIntegrationId = value$ != null ? value$.toString() : null; break;
    case 1: submissionType = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'applicationIntegrationId' field.
   * @return The value of the 'applicationIntegrationId' field.
   */
  public java.lang.String getApplicationIntegrationId() {
    return applicationIntegrationId;
  }


  /**
   * Sets the value of the 'applicationIntegrationId' field.
   * @param value the value to set.
   */
  public void setApplicationIntegrationId(java.lang.String value) {
    this.applicationIntegrationId = value;
  }

  /**
   * Gets the value of the 'submissionType' field.
   * @return The value of the 'submissionType' field.
   */
  public java.lang.String getSubmissionType() {
    return submissionType;
  }


  /**
   * Sets the value of the 'submissionType' field.
   * @param value the value to set.
   */
  public void setSubmissionType(java.lang.String value) {
    this.submissionType = value;
  }

  /**
   * Creates a new CreateSubmissionEvent RecordBuilder.
   * @return A new CreateSubmissionEvent RecordBuilder
   */
  public static ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent.Builder newBuilder() {
    return new ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent.Builder();
  }

  /**
   * Creates a new CreateSubmissionEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CreateSubmissionEvent RecordBuilder
   */
  public static ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent.Builder newBuilder(ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent.Builder other) {
    if (other == null) {
      return new ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent.Builder();
    } else {
      return new ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent.Builder(other);
    }
  }

  /**
   * Creates a new CreateSubmissionEvent RecordBuilder by copying an existing CreateSubmissionEvent instance.
   * @param other The existing instance to copy.
   * @return A new CreateSubmissionEvent RecordBuilder
   */
  public static ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent.Builder newBuilder(ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent other) {
    if (other == null) {
      return new ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent.Builder();
    } else {
      return new ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for CreateSubmissionEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CreateSubmissionEvent>
    implements org.apache.avro.data.RecordBuilder<CreateSubmissionEvent> {

    private java.lang.String applicationIntegrationId;
    private java.lang.String submissionType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.applicationIntegrationId)) {
        this.applicationIntegrationId = data().deepCopy(fields()[0].schema(), other.applicationIntegrationId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.submissionType)) {
        this.submissionType = data().deepCopy(fields()[1].schema(), other.submissionType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing CreateSubmissionEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.applicationIntegrationId)) {
        this.applicationIntegrationId = data().deepCopy(fields()[0].schema(), other.applicationIntegrationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.submissionType)) {
        this.submissionType = data().deepCopy(fields()[1].schema(), other.submissionType);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'applicationIntegrationId' field.
      * @return The value.
      */
    public java.lang.String getApplicationIntegrationId() {
      return applicationIntegrationId;
    }


    /**
      * Sets the value of the 'applicationIntegrationId' field.
      * @param value The value of 'applicationIntegrationId'.
      * @return This builder.
      */
    public ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent.Builder setApplicationIntegrationId(java.lang.String value) {
      validate(fields()[0], value);
      this.applicationIntegrationId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'applicationIntegrationId' field has been set.
      * @return True if the 'applicationIntegrationId' field has been set, false otherwise.
      */
    public boolean hasApplicationIntegrationId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'applicationIntegrationId' field.
      * @return This builder.
      */
    public ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent.Builder clearApplicationIntegrationId() {
      applicationIntegrationId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'submissionType' field.
      * @return The value.
      */
    public java.lang.String getSubmissionType() {
      return submissionType;
    }


    /**
      * Sets the value of the 'submissionType' field.
      * @param value The value of 'submissionType'.
      * @return This builder.
      */
    public ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent.Builder setSubmissionType(java.lang.String value) {
      validate(fields()[1], value);
      this.submissionType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'submissionType' field has been set.
      * @return True if the 'submissionType' field has been set, false otherwise.
      */
    public boolean hasSubmissionType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'submissionType' field.
      * @return This builder.
      */
    public ru.tinkoff.bpm.pledge.submission.registration.process.CreateSubmissionEvent.Builder clearSubmissionType() {
      submissionType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CreateSubmissionEvent build() {
      try {
        CreateSubmissionEvent record = new CreateSubmissionEvent();
        record.applicationIntegrationId = fieldSetFlags()[0] ? this.applicationIntegrationId : (java.lang.String) defaultValue(fields()[0]);
        record.submissionType = fieldSetFlags()[1] ? this.submissionType : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CreateSubmissionEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<CreateSubmissionEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CreateSubmissionEvent>
    READER$ = (org.apache.avro.io.DatumReader<CreateSubmissionEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.applicationIntegrationId);

    out.writeString(this.submissionType);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.applicationIntegrationId = in.readString();

      this.submissionType = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.applicationIntegrationId = in.readString();
          break;

        case 1:
          this.submissionType = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










