/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.tinkoff.bpm.pledge.submission.registration.process;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MortgageRefinanceBankSigningEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2439727628491111034L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MortgageRefinanceBankSigningEvent\",\"namespace\":\"ru.tinkoff.bpm.pledge.submission.registration.process\",\"fields\":[{\"name\":\"submissionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MortgageRefinanceBankSigningEvent> ENCODER =
      new BinaryMessageEncoder<MortgageRefinanceBankSigningEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MortgageRefinanceBankSigningEvent> DECODER =
      new BinaryMessageDecoder<MortgageRefinanceBankSigningEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MortgageRefinanceBankSigningEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MortgageRefinanceBankSigningEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MortgageRefinanceBankSigningEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MortgageRefinanceBankSigningEvent>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MortgageRefinanceBankSigningEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MortgageRefinanceBankSigningEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MortgageRefinanceBankSigningEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MortgageRefinanceBankSigningEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String submissionId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MortgageRefinanceBankSigningEvent() {}

  /**
   * All-args constructor.
   * @param submissionId The new value for submissionId
   */
  public MortgageRefinanceBankSigningEvent(java.lang.String submissionId) {
    this.submissionId = submissionId;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return submissionId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: submissionId = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'submissionId' field.
   * @return The value of the 'submissionId' field.
   */
  public java.lang.String getSubmissionId() {
    return submissionId;
  }


  /**
   * Sets the value of the 'submissionId' field.
   * @param value the value to set.
   */
  public void setSubmissionId(java.lang.String value) {
    this.submissionId = value;
  }

  /**
   * Creates a new MortgageRefinanceBankSigningEvent RecordBuilder.
   * @return A new MortgageRefinanceBankSigningEvent RecordBuilder
   */
  public static ru.tinkoff.bpm.pledge.submission.registration.process.MortgageRefinanceBankSigningEvent.Builder newBuilder() {
    return new ru.tinkoff.bpm.pledge.submission.registration.process.MortgageRefinanceBankSigningEvent.Builder();
  }

  /**
   * Creates a new MortgageRefinanceBankSigningEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MortgageRefinanceBankSigningEvent RecordBuilder
   */
  public static ru.tinkoff.bpm.pledge.submission.registration.process.MortgageRefinanceBankSigningEvent.Builder newBuilder(ru.tinkoff.bpm.pledge.submission.registration.process.MortgageRefinanceBankSigningEvent.Builder other) {
    if (other == null) {
      return new ru.tinkoff.bpm.pledge.submission.registration.process.MortgageRefinanceBankSigningEvent.Builder();
    } else {
      return new ru.tinkoff.bpm.pledge.submission.registration.process.MortgageRefinanceBankSigningEvent.Builder(other);
    }
  }

  /**
   * Creates a new MortgageRefinanceBankSigningEvent RecordBuilder by copying an existing MortgageRefinanceBankSigningEvent instance.
   * @param other The existing instance to copy.
   * @return A new MortgageRefinanceBankSigningEvent RecordBuilder
   */
  public static ru.tinkoff.bpm.pledge.submission.registration.process.MortgageRefinanceBankSigningEvent.Builder newBuilder(ru.tinkoff.bpm.pledge.submission.registration.process.MortgageRefinanceBankSigningEvent other) {
    if (other == null) {
      return new ru.tinkoff.bpm.pledge.submission.registration.process.MortgageRefinanceBankSigningEvent.Builder();
    } else {
      return new ru.tinkoff.bpm.pledge.submission.registration.process.MortgageRefinanceBankSigningEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for MortgageRefinanceBankSigningEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MortgageRefinanceBankSigningEvent>
    implements org.apache.avro.data.RecordBuilder<MortgageRefinanceBankSigningEvent> {

    private java.lang.String submissionId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ru.tinkoff.bpm.pledge.submission.registration.process.MortgageRefinanceBankSigningEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.submissionId)) {
        this.submissionId = data().deepCopy(fields()[0].schema(), other.submissionId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing MortgageRefinanceBankSigningEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(ru.tinkoff.bpm.pledge.submission.registration.process.MortgageRefinanceBankSigningEvent other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.submissionId)) {
        this.submissionId = data().deepCopy(fields()[0].schema(), other.submissionId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'submissionId' field.
      * @return The value.
      */
    public java.lang.String getSubmissionId() {
      return submissionId;
    }


    /**
      * Sets the value of the 'submissionId' field.
      * @param value The value of 'submissionId'.
      * @return This builder.
      */
    public ru.tinkoff.bpm.pledge.submission.registration.process.MortgageRefinanceBankSigningEvent.Builder setSubmissionId(java.lang.String value) {
      validate(fields()[0], value);
      this.submissionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'submissionId' field has been set.
      * @return True if the 'submissionId' field has been set, false otherwise.
      */
    public boolean hasSubmissionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'submissionId' field.
      * @return This builder.
      */
    public ru.tinkoff.bpm.pledge.submission.registration.process.MortgageRefinanceBankSigningEvent.Builder clearSubmissionId() {
      submissionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MortgageRefinanceBankSigningEvent build() {
      try {
        MortgageRefinanceBankSigningEvent record = new MortgageRefinanceBankSigningEvent();
        record.submissionId = fieldSetFlags()[0] ? this.submissionId : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MortgageRefinanceBankSigningEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<MortgageRefinanceBankSigningEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MortgageRefinanceBankSigningEvent>
    READER$ = (org.apache.avro.io.DatumReader<MortgageRefinanceBankSigningEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.submissionId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.submissionId = in.readString();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.submissionId = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










