/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.tinkoff.sme.cryptobpm.responses;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ErrorDescription extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5937647433587833040L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ErrorDescription\",\"namespace\":\"ru.tinkoff.sme.cryptobpm.responses\",\"fields\":[{\"name\":\"errorCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"errorMessage\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ErrorDescription> ENCODER =
      new BinaryMessageEncoder<ErrorDescription>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ErrorDescription> DECODER =
      new BinaryMessageDecoder<ErrorDescription>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ErrorDescription> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ErrorDescription> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ErrorDescription> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ErrorDescription>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ErrorDescription to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ErrorDescription from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ErrorDescription instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ErrorDescription fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String errorCode;
  @Deprecated public java.lang.String errorMessage;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ErrorDescription() {}

  /**
   * All-args constructor.
   * @param errorCode The new value for errorCode
   * @param errorMessage The new value for errorMessage
   */
  public ErrorDescription(java.lang.String errorCode, java.lang.String errorMessage) {
    this.errorCode = errorCode;
    this.errorMessage = errorMessage;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return errorCode;
    case 1: return errorMessage;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: errorCode = value$ != null ? value$.toString() : null; break;
    case 1: errorMessage = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'errorCode' field.
   * @return The value of the 'errorCode' field.
   */
  public java.lang.String getErrorCode() {
    return errorCode;
  }


  /**
   * Sets the value of the 'errorCode' field.
   * @param value the value to set.
   */
  public void setErrorCode(java.lang.String value) {
    this.errorCode = value;
  }

  /**
   * Gets the value of the 'errorMessage' field.
   * @return The value of the 'errorMessage' field.
   */
  public java.lang.String getErrorMessage() {
    return errorMessage;
  }


  /**
   * Sets the value of the 'errorMessage' field.
   * @param value the value to set.
   */
  public void setErrorMessage(java.lang.String value) {
    this.errorMessage = value;
  }

  /**
   * Creates a new ErrorDescription RecordBuilder.
   * @return A new ErrorDescription RecordBuilder
   */
  public static ru.tinkoff.sme.cryptobpm.responses.ErrorDescription.Builder newBuilder() {
    return new ru.tinkoff.sme.cryptobpm.responses.ErrorDescription.Builder();
  }

  /**
   * Creates a new ErrorDescription RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ErrorDescription RecordBuilder
   */
  public static ru.tinkoff.sme.cryptobpm.responses.ErrorDescription.Builder newBuilder(ru.tinkoff.sme.cryptobpm.responses.ErrorDescription.Builder other) {
    if (other == null) {
      return new ru.tinkoff.sme.cryptobpm.responses.ErrorDescription.Builder();
    } else {
      return new ru.tinkoff.sme.cryptobpm.responses.ErrorDescription.Builder(other);
    }
  }

  /**
   * Creates a new ErrorDescription RecordBuilder by copying an existing ErrorDescription instance.
   * @param other The existing instance to copy.
   * @return A new ErrorDescription RecordBuilder
   */
  public static ru.tinkoff.sme.cryptobpm.responses.ErrorDescription.Builder newBuilder(ru.tinkoff.sme.cryptobpm.responses.ErrorDescription other) {
    if (other == null) {
      return new ru.tinkoff.sme.cryptobpm.responses.ErrorDescription.Builder();
    } else {
      return new ru.tinkoff.sme.cryptobpm.responses.ErrorDescription.Builder(other);
    }
  }

  /**
   * RecordBuilder for ErrorDescription instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ErrorDescription>
    implements org.apache.avro.data.RecordBuilder<ErrorDescription> {

    private java.lang.String errorCode;
    private java.lang.String errorMessage;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ru.tinkoff.sme.cryptobpm.responses.ErrorDescription.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.errorCode)) {
        this.errorCode = data().deepCopy(fields()[0].schema(), other.errorCode);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[1].schema(), other.errorMessage);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ErrorDescription instance
     * @param other The existing instance to copy.
     */
    private Builder(ru.tinkoff.sme.cryptobpm.responses.ErrorDescription other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.errorCode)) {
        this.errorCode = data().deepCopy(fields()[0].schema(), other.errorCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[1].schema(), other.errorMessage);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'errorCode' field.
      * @return The value.
      */
    public java.lang.String getErrorCode() {
      return errorCode;
    }


    /**
      * Sets the value of the 'errorCode' field.
      * @param value The value of 'errorCode'.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.responses.ErrorDescription.Builder setErrorCode(java.lang.String value) {
      validate(fields()[0], value);
      this.errorCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'errorCode' field has been set.
      * @return True if the 'errorCode' field has been set, false otherwise.
      */
    public boolean hasErrorCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'errorCode' field.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.responses.ErrorDescription.Builder clearErrorCode() {
      errorCode = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorMessage' field.
      * @return The value.
      */
    public java.lang.String getErrorMessage() {
      return errorMessage;
    }


    /**
      * Sets the value of the 'errorMessage' field.
      * @param value The value of 'errorMessage'.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.responses.ErrorDescription.Builder setErrorMessage(java.lang.String value) {
      validate(fields()[1], value);
      this.errorMessage = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'errorMessage' field has been set.
      * @return True if the 'errorMessage' field has been set, false otherwise.
      */
    public boolean hasErrorMessage() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'errorMessage' field.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.responses.ErrorDescription.Builder clearErrorMessage() {
      errorMessage = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ErrorDescription build() {
      try {
        ErrorDescription record = new ErrorDescription();
        record.errorCode = fieldSetFlags()[0] ? this.errorCode : (java.lang.String) defaultValue(fields()[0]);
        record.errorMessage = fieldSetFlags()[1] ? this.errorMessage : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ErrorDescription>
    WRITER$ = (org.apache.avro.io.DatumWriter<ErrorDescription>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ErrorDescription>
    READER$ = (org.apache.avro.io.DatumReader<ErrorDescription>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.errorCode);

    if (this.errorMessage == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.errorMessage);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.errorCode = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.errorMessage = null;
      } else {
        this.errorMessage = in.readString();
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.errorCode = in.readString();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.errorMessage = null;
          } else {
            this.errorMessage = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










