/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.tinkoff.sme.cryptobpm.requests;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Entity extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5000090191309966512L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Entity\",\"namespace\":\"ru.tinkoff.sme.cryptobpm.requests\",\"fields\":[{\"name\":\"innUl\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"ogrn\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"snils\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Entity> ENCODER =
      new BinaryMessageEncoder<Entity>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Entity> DECODER =
      new BinaryMessageDecoder<Entity>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Entity> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Entity> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Entity> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Entity>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Entity to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Entity from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Entity instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Entity fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String innUl;
  @Deprecated public java.lang.String ogrn;
  @Deprecated public java.lang.String snils;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Entity() {}

  /**
   * All-args constructor.
   * @param innUl The new value for innUl
   * @param ogrn The new value for ogrn
   * @param snils The new value for snils
   */
  public Entity(java.lang.String innUl, java.lang.String ogrn, java.lang.String snils) {
    this.innUl = innUl;
    this.ogrn = ogrn;
    this.snils = snils;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return innUl;
    case 1: return ogrn;
    case 2: return snils;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: innUl = value$ != null ? value$.toString() : null; break;
    case 1: ogrn = value$ != null ? value$.toString() : null; break;
    case 2: snils = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'innUl' field.
   * @return The value of the 'innUl' field.
   */
  public java.lang.String getInnUl() {
    return innUl;
  }


  /**
   * Sets the value of the 'innUl' field.
   * @param value the value to set.
   */
  public void setInnUl(java.lang.String value) {
    this.innUl = value;
  }

  /**
   * Gets the value of the 'ogrn' field.
   * @return The value of the 'ogrn' field.
   */
  public java.lang.String getOgrn() {
    return ogrn;
  }


  /**
   * Sets the value of the 'ogrn' field.
   * @param value the value to set.
   */
  public void setOgrn(java.lang.String value) {
    this.ogrn = value;
  }

  /**
   * Gets the value of the 'snils' field.
   * @return The value of the 'snils' field.
   */
  public java.lang.String getSnils() {
    return snils;
  }


  /**
   * Sets the value of the 'snils' field.
   * @param value the value to set.
   */
  public void setSnils(java.lang.String value) {
    this.snils = value;
  }

  /**
   * Creates a new Entity RecordBuilder.
   * @return A new Entity RecordBuilder
   */
  public static ru.tinkoff.sme.cryptobpm.requests.Entity.Builder newBuilder() {
    return new ru.tinkoff.sme.cryptobpm.requests.Entity.Builder();
  }

  /**
   * Creates a new Entity RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Entity RecordBuilder
   */
  public static ru.tinkoff.sme.cryptobpm.requests.Entity.Builder newBuilder(ru.tinkoff.sme.cryptobpm.requests.Entity.Builder other) {
    if (other == null) {
      return new ru.tinkoff.sme.cryptobpm.requests.Entity.Builder();
    } else {
      return new ru.tinkoff.sme.cryptobpm.requests.Entity.Builder(other);
    }
  }

  /**
   * Creates a new Entity RecordBuilder by copying an existing Entity instance.
   * @param other The existing instance to copy.
   * @return A new Entity RecordBuilder
   */
  public static ru.tinkoff.sme.cryptobpm.requests.Entity.Builder newBuilder(ru.tinkoff.sme.cryptobpm.requests.Entity other) {
    if (other == null) {
      return new ru.tinkoff.sme.cryptobpm.requests.Entity.Builder();
    } else {
      return new ru.tinkoff.sme.cryptobpm.requests.Entity.Builder(other);
    }
  }

  /**
   * RecordBuilder for Entity instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Entity>
    implements org.apache.avro.data.RecordBuilder<Entity> {

    private java.lang.String innUl;
    private java.lang.String ogrn;
    private java.lang.String snils;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ru.tinkoff.sme.cryptobpm.requests.Entity.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.innUl)) {
        this.innUl = data().deepCopy(fields()[0].schema(), other.innUl);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.ogrn)) {
        this.ogrn = data().deepCopy(fields()[1].schema(), other.ogrn);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.snils)) {
        this.snils = data().deepCopy(fields()[2].schema(), other.snils);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Entity instance
     * @param other The existing instance to copy.
     */
    private Builder(ru.tinkoff.sme.cryptobpm.requests.Entity other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.innUl)) {
        this.innUl = data().deepCopy(fields()[0].schema(), other.innUl);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ogrn)) {
        this.ogrn = data().deepCopy(fields()[1].schema(), other.ogrn);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.snils)) {
        this.snils = data().deepCopy(fields()[2].schema(), other.snils);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'innUl' field.
      * @return The value.
      */
    public java.lang.String getInnUl() {
      return innUl;
    }


    /**
      * Sets the value of the 'innUl' field.
      * @param value The value of 'innUl'.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.requests.Entity.Builder setInnUl(java.lang.String value) {
      validate(fields()[0], value);
      this.innUl = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'innUl' field has been set.
      * @return True if the 'innUl' field has been set, false otherwise.
      */
    public boolean hasInnUl() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'innUl' field.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.requests.Entity.Builder clearInnUl() {
      innUl = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ogrn' field.
      * @return The value.
      */
    public java.lang.String getOgrn() {
      return ogrn;
    }


    /**
      * Sets the value of the 'ogrn' field.
      * @param value The value of 'ogrn'.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.requests.Entity.Builder setOgrn(java.lang.String value) {
      validate(fields()[1], value);
      this.ogrn = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ogrn' field has been set.
      * @return True if the 'ogrn' field has been set, false otherwise.
      */
    public boolean hasOgrn() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ogrn' field.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.requests.Entity.Builder clearOgrn() {
      ogrn = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'snils' field.
      * @return The value.
      */
    public java.lang.String getSnils() {
      return snils;
    }


    /**
      * Sets the value of the 'snils' field.
      * @param value The value of 'snils'.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.requests.Entity.Builder setSnils(java.lang.String value) {
      validate(fields()[2], value);
      this.snils = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'snils' field has been set.
      * @return True if the 'snils' field has been set, false otherwise.
      */
    public boolean hasSnils() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'snils' field.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.requests.Entity.Builder clearSnils() {
      snils = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Entity build() {
      try {
        Entity record = new Entity();
        record.innUl = fieldSetFlags()[0] ? this.innUl : (java.lang.String) defaultValue(fields()[0]);
        record.ogrn = fieldSetFlags()[1] ? this.ogrn : (java.lang.String) defaultValue(fields()[1]);
        record.snils = fieldSetFlags()[2] ? this.snils : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Entity>
    WRITER$ = (org.apache.avro.io.DatumWriter<Entity>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Entity>
    READER$ = (org.apache.avro.io.DatumReader<Entity>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.innUl);

    if (this.ogrn == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.ogrn);
    }

    if (this.snils == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.snils);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.innUl = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.ogrn = null;
      } else {
        this.ogrn = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.snils = null;
      } else {
        this.snils = in.readString();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.innUl = in.readString();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.ogrn = null;
          } else {
            this.ogrn = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.snils = null;
          } else {
            this.snils = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










