/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.tinkoff.sme.cryptobpm.requests;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class FileRef extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 233971834423946872L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FileRef\",\"namespace\":\"ru.tinkoff.sme.cryptobpm.requests\",\"fields\":[{\"name\":\"fileId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"uri\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"signatureUri\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"meta\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"FileMeta\",\"fields\":[{\"name\":\"fileName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<FileRef> ENCODER =
      new BinaryMessageEncoder<FileRef>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<FileRef> DECODER =
      new BinaryMessageDecoder<FileRef>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<FileRef> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<FileRef> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<FileRef> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<FileRef>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this FileRef to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a FileRef from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a FileRef instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static FileRef fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String fileId;
  @Deprecated public java.lang.String uri;
  @Deprecated public java.lang.String signatureUri;
  @Deprecated public ru.tinkoff.sme.cryptobpm.requests.FileMeta meta;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FileRef() {}

  /**
   * All-args constructor.
   * @param fileId The new value for fileId
   * @param uri The new value for uri
   * @param signatureUri The new value for signatureUri
   * @param meta The new value for meta
   */
  public FileRef(java.lang.String fileId, java.lang.String uri, java.lang.String signatureUri, ru.tinkoff.sme.cryptobpm.requests.FileMeta meta) {
    this.fileId = fileId;
    this.uri = uri;
    this.signatureUri = signatureUri;
    this.meta = meta;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return fileId;
    case 1: return uri;
    case 2: return signatureUri;
    case 3: return meta;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: fileId = value$ != null ? value$.toString() : null; break;
    case 1: uri = value$ != null ? value$.toString() : null; break;
    case 2: signatureUri = value$ != null ? value$.toString() : null; break;
    case 3: meta = (ru.tinkoff.sme.cryptobpm.requests.FileMeta)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'fileId' field.
   * @return The value of the 'fileId' field.
   */
  public java.lang.String getFileId() {
    return fileId;
  }


  /**
   * Sets the value of the 'fileId' field.
   * @param value the value to set.
   */
  public void setFileId(java.lang.String value) {
    this.fileId = value;
  }

  /**
   * Gets the value of the 'uri' field.
   * @return The value of the 'uri' field.
   */
  public java.lang.String getUri() {
    return uri;
  }


  /**
   * Sets the value of the 'uri' field.
   * @param value the value to set.
   */
  public void setUri(java.lang.String value) {
    this.uri = value;
  }

  /**
   * Gets the value of the 'signatureUri' field.
   * @return The value of the 'signatureUri' field.
   */
  public java.lang.String getSignatureUri() {
    return signatureUri;
  }


  /**
   * Sets the value of the 'signatureUri' field.
   * @param value the value to set.
   */
  public void setSignatureUri(java.lang.String value) {
    this.signatureUri = value;
  }

  /**
   * Gets the value of the 'meta' field.
   * @return The value of the 'meta' field.
   */
  public ru.tinkoff.sme.cryptobpm.requests.FileMeta getMeta() {
    return meta;
  }


  /**
   * Sets the value of the 'meta' field.
   * @param value the value to set.
   */
  public void setMeta(ru.tinkoff.sme.cryptobpm.requests.FileMeta value) {
    this.meta = value;
  }

  /**
   * Creates a new FileRef RecordBuilder.
   * @return A new FileRef RecordBuilder
   */
  public static ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder newBuilder() {
    return new ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder();
  }

  /**
   * Creates a new FileRef RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FileRef RecordBuilder
   */
  public static ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder newBuilder(ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder other) {
    if (other == null) {
      return new ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder();
    } else {
      return new ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder(other);
    }
  }

  /**
   * Creates a new FileRef RecordBuilder by copying an existing FileRef instance.
   * @param other The existing instance to copy.
   * @return A new FileRef RecordBuilder
   */
  public static ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder newBuilder(ru.tinkoff.sme.cryptobpm.requests.FileRef other) {
    if (other == null) {
      return new ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder();
    } else {
      return new ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder(other);
    }
  }

  /**
   * RecordBuilder for FileRef instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FileRef>
    implements org.apache.avro.data.RecordBuilder<FileRef> {

    private java.lang.String fileId;
    private java.lang.String uri;
    private java.lang.String signatureUri;
    private ru.tinkoff.sme.cryptobpm.requests.FileMeta meta;
    private ru.tinkoff.sme.cryptobpm.requests.FileMeta.Builder metaBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.fileId)) {
        this.fileId = data().deepCopy(fields()[0].schema(), other.fileId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.uri)) {
        this.uri = data().deepCopy(fields()[1].schema(), other.uri);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.signatureUri)) {
        this.signatureUri = data().deepCopy(fields()[2].schema(), other.signatureUri);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.meta)) {
        this.meta = data().deepCopy(fields()[3].schema(), other.meta);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (other.hasMetaBuilder()) {
        this.metaBuilder = ru.tinkoff.sme.cryptobpm.requests.FileMeta.newBuilder(other.getMetaBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing FileRef instance
     * @param other The existing instance to copy.
     */
    private Builder(ru.tinkoff.sme.cryptobpm.requests.FileRef other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.fileId)) {
        this.fileId = data().deepCopy(fields()[0].schema(), other.fileId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.uri)) {
        this.uri = data().deepCopy(fields()[1].schema(), other.uri);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.signatureUri)) {
        this.signatureUri = data().deepCopy(fields()[2].schema(), other.signatureUri);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.meta)) {
        this.meta = data().deepCopy(fields()[3].schema(), other.meta);
        fieldSetFlags()[3] = true;
      }
      this.metaBuilder = null;
    }

    /**
      * Gets the value of the 'fileId' field.
      * @return The value.
      */
    public java.lang.String getFileId() {
      return fileId;
    }


    /**
      * Sets the value of the 'fileId' field.
      * @param value The value of 'fileId'.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder setFileId(java.lang.String value) {
      validate(fields()[0], value);
      this.fileId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'fileId' field has been set.
      * @return True if the 'fileId' field has been set, false otherwise.
      */
    public boolean hasFileId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'fileId' field.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder clearFileId() {
      fileId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'uri' field.
      * @return The value.
      */
    public java.lang.String getUri() {
      return uri;
    }


    /**
      * Sets the value of the 'uri' field.
      * @param value The value of 'uri'.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder setUri(java.lang.String value) {
      validate(fields()[1], value);
      this.uri = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'uri' field has been set.
      * @return True if the 'uri' field has been set, false otherwise.
      */
    public boolean hasUri() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'uri' field.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder clearUri() {
      uri = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'signatureUri' field.
      * @return The value.
      */
    public java.lang.String getSignatureUri() {
      return signatureUri;
    }


    /**
      * Sets the value of the 'signatureUri' field.
      * @param value The value of 'signatureUri'.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder setSignatureUri(java.lang.String value) {
      validate(fields()[2], value);
      this.signatureUri = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'signatureUri' field has been set.
      * @return True if the 'signatureUri' field has been set, false otherwise.
      */
    public boolean hasSignatureUri() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'signatureUri' field.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder clearSignatureUri() {
      signatureUri = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'meta' field.
      * @return The value.
      */
    public ru.tinkoff.sme.cryptobpm.requests.FileMeta getMeta() {
      return meta;
    }


    /**
      * Sets the value of the 'meta' field.
      * @param value The value of 'meta'.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder setMeta(ru.tinkoff.sme.cryptobpm.requests.FileMeta value) {
      validate(fields()[3], value);
      this.metaBuilder = null;
      this.meta = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'meta' field has been set.
      * @return True if the 'meta' field has been set, false otherwise.
      */
    public boolean hasMeta() {
      return fieldSetFlags()[3];
    }

    /**
     * Gets the Builder instance for the 'meta' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public ru.tinkoff.sme.cryptobpm.requests.FileMeta.Builder getMetaBuilder() {
      if (metaBuilder == null) {
        if (hasMeta()) {
          setMetaBuilder(ru.tinkoff.sme.cryptobpm.requests.FileMeta.newBuilder(meta));
        } else {
          setMetaBuilder(ru.tinkoff.sme.cryptobpm.requests.FileMeta.newBuilder());
        }
      }
      return metaBuilder;
    }

    /**
     * Sets the Builder instance for the 'meta' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder setMetaBuilder(ru.tinkoff.sme.cryptobpm.requests.FileMeta.Builder value) {
      clearMeta();
      metaBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'meta' field has an active Builder instance
     * @return True if the 'meta' field has an active Builder instance
     */
    public boolean hasMetaBuilder() {
      return metaBuilder != null;
    }

    /**
      * Clears the value of the 'meta' field.
      * @return This builder.
      */
    public ru.tinkoff.sme.cryptobpm.requests.FileRef.Builder clearMeta() {
      meta = null;
      metaBuilder = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public FileRef build() {
      try {
        FileRef record = new FileRef();
        record.fileId = fieldSetFlags()[0] ? this.fileId : (java.lang.String) defaultValue(fields()[0]);
        record.uri = fieldSetFlags()[1] ? this.uri : (java.lang.String) defaultValue(fields()[1]);
        record.signatureUri = fieldSetFlags()[2] ? this.signatureUri : (java.lang.String) defaultValue(fields()[2]);
        if (metaBuilder != null) {
          try {
            record.meta = this.metaBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("meta"));
            throw e;
          }
        } else {
          record.meta = fieldSetFlags()[3] ? this.meta : (ru.tinkoff.sme.cryptobpm.requests.FileMeta) defaultValue(fields()[3]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<FileRef>
    WRITER$ = (org.apache.avro.io.DatumWriter<FileRef>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<FileRef>
    READER$ = (org.apache.avro.io.DatumReader<FileRef>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.fileId);

    out.writeString(this.uri);

    if (this.signatureUri == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.signatureUri);
    }

    if (this.meta == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      this.meta.customEncode(out);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.fileId = in.readString();

      this.uri = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.signatureUri = null;
      } else {
        this.signatureUri = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.meta = null;
      } else {
        if (this.meta == null) {
          this.meta = new ru.tinkoff.sme.cryptobpm.requests.FileMeta();
        }
        this.meta.customDecode(in);
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.fileId = in.readString();
          break;

        case 1:
          this.uri = in.readString();
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.signatureUri = null;
          } else {
            this.signatureUri = in.readString();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.meta = null;
          } else {
            if (this.meta == null) {
              this.meta = new ru.tinkoff.sme.cryptobpm.requests.FileMeta();
            }
            this.meta.customDecode(in);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










