/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.tinkoff.sme.cryptobpm.requests;
@org.apache.avro.specific.AvroGenerated
public enum SelectStrategy implements org.apache.avro.generic.GenericEnumSymbol<SelectStrategy> {
  OLDEST_FIRST, NEWEST_FIRST  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SelectStrategy\",\"namespace\":\"ru.tinkoff.sme.cryptobpm.requests\",\"symbols\":[\"OLDEST_FIRST\",\"NEWEST_FIRST\"],\"default\":\"OLDEST_FIRST\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
