/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.tinkoff.bpm.topdsssigningprocess.model.sign;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DocumentSignRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1599729025960480096L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DocumentSignRequest\",\"namespace\":\"ru.tinkoff.bpm.topdsssigningprocess.model.sign\",\"fields\":[{\"name\":\"requestId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"logicalType\":\"uuid\"},{\"name\":\"system\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"submissionId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"signingSide\",\"type\":{\"type\":\"enum\",\"name\":\"SigningSide\",\"symbols\":[\"CLIENT\",\"BANK\"]}},{\"name\":\"inn\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"snils\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"documents\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"RequestedDocument\",\"fields\":[{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"RequestedDocumentType\",\"symbols\":[\"MORTGAGE_AGREEMENT\",\"APPLICATION_FORM\",\"INDIVIDUAL_CONDITIONS\",\"CLIENT_APPLICATION_ROSREESTR\",\"BANK_APPLICATION_ROSREESTR\",\"CONTAINER_DESCRIPTION\"]}},{\"name\":\"documentUri\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"signatureUri\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"finalSigning\",\"type\":\"boolean\",\"default\":true}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DocumentSignRequest> ENCODER =
      new BinaryMessageEncoder<DocumentSignRequest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DocumentSignRequest> DECODER =
      new BinaryMessageDecoder<DocumentSignRequest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DocumentSignRequest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DocumentSignRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DocumentSignRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DocumentSignRequest>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DocumentSignRequest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DocumentSignRequest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DocumentSignRequest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DocumentSignRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String requestId;
  @Deprecated public java.lang.String system;
  @Deprecated public java.lang.String submissionId;
  @Deprecated public ru.tinkoff.bpm.topdsssigningprocess.model.sign.SigningSide signingSide;
  @Deprecated public java.lang.String inn;
  @Deprecated public java.lang.String snils;
  @Deprecated public java.util.List<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument> documents;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DocumentSignRequest() {}

  /**
   * All-args constructor.
   * @param requestId The new value for requestId
   * @param system The new value for system
   * @param submissionId The new value for submissionId
   * @param signingSide The new value for signingSide
   * @param inn The new value for inn
   * @param snils The new value for snils
   * @param documents The new value for documents
   */
  public DocumentSignRequest(java.lang.String requestId, java.lang.String system, java.lang.String submissionId, ru.tinkoff.bpm.topdsssigningprocess.model.sign.SigningSide signingSide, java.lang.String inn, java.lang.String snils, java.util.List<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument> documents) {
    this.requestId = requestId;
    this.system = system;
    this.submissionId = submissionId;
    this.signingSide = signingSide;
    this.inn = inn;
    this.snils = snils;
    this.documents = documents;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return requestId;
    case 1: return system;
    case 2: return submissionId;
    case 3: return signingSide;
    case 4: return inn;
    case 5: return snils;
    case 6: return documents;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: requestId = value$ != null ? value$.toString() : null; break;
    case 1: system = value$ != null ? value$.toString() : null; break;
    case 2: submissionId = value$ != null ? value$.toString() : null; break;
    case 3: signingSide = (ru.tinkoff.bpm.topdsssigningprocess.model.sign.SigningSide)value$; break;
    case 4: inn = value$ != null ? value$.toString() : null; break;
    case 5: snils = value$ != null ? value$.toString() : null; break;
    case 6: documents = (java.util.List<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'requestId' field.
   * @return The value of the 'requestId' field.
   */
  public java.lang.String getRequestId() {
    return requestId;
  }


  /**
   * Sets the value of the 'requestId' field.
   * @param value the value to set.
   */
  public void setRequestId(java.lang.String value) {
    this.requestId = value;
  }

  /**
   * Gets the value of the 'system' field.
   * @return The value of the 'system' field.
   */
  public java.lang.String getSystem() {
    return system;
  }


  /**
   * Sets the value of the 'system' field.
   * @param value the value to set.
   */
  public void setSystem(java.lang.String value) {
    this.system = value;
  }

  /**
   * Gets the value of the 'submissionId' field.
   * @return The value of the 'submissionId' field.
   */
  public java.lang.String getSubmissionId() {
    return submissionId;
  }


  /**
   * Sets the value of the 'submissionId' field.
   * @param value the value to set.
   */
  public void setSubmissionId(java.lang.String value) {
    this.submissionId = value;
  }

  /**
   * Gets the value of the 'signingSide' field.
   * @return The value of the 'signingSide' field.
   */
  public ru.tinkoff.bpm.topdsssigningprocess.model.sign.SigningSide getSigningSide() {
    return signingSide;
  }


  /**
   * Sets the value of the 'signingSide' field.
   * @param value the value to set.
   */
  public void setSigningSide(ru.tinkoff.bpm.topdsssigningprocess.model.sign.SigningSide value) {
    this.signingSide = value;
  }

  /**
   * Gets the value of the 'inn' field.
   * @return The value of the 'inn' field.
   */
  public java.lang.String getInn() {
    return inn;
  }


  /**
   * Sets the value of the 'inn' field.
   * @param value the value to set.
   */
  public void setInn(java.lang.String value) {
    this.inn = value;
  }

  /**
   * Gets the value of the 'snils' field.
   * @return The value of the 'snils' field.
   */
  public java.lang.String getSnils() {
    return snils;
  }


  /**
   * Sets the value of the 'snils' field.
   * @param value the value to set.
   */
  public void setSnils(java.lang.String value) {
    this.snils = value;
  }

  /**
   * Gets the value of the 'documents' field.
   * @return The value of the 'documents' field.
   */
  public java.util.List<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument> getDocuments() {
    return documents;
  }


  /**
   * Sets the value of the 'documents' field.
   * @param value the value to set.
   */
  public void setDocuments(java.util.List<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument> value) {
    this.documents = value;
  }

  /**
   * Creates a new DocumentSignRequest RecordBuilder.
   * @return A new DocumentSignRequest RecordBuilder
   */
  public static ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder newBuilder() {
    return new ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder();
  }

  /**
   * Creates a new DocumentSignRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DocumentSignRequest RecordBuilder
   */
  public static ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder newBuilder(ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder other) {
    if (other == null) {
      return new ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder();
    } else {
      return new ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder(other);
    }
  }

  /**
   * Creates a new DocumentSignRequest RecordBuilder by copying an existing DocumentSignRequest instance.
   * @param other The existing instance to copy.
   * @return A new DocumentSignRequest RecordBuilder
   */
  public static ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder newBuilder(ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest other) {
    if (other == null) {
      return new ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder();
    } else {
      return new ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder(other);
    }
  }

  /**
   * RecordBuilder for DocumentSignRequest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DocumentSignRequest>
    implements org.apache.avro.data.RecordBuilder<DocumentSignRequest> {

    private java.lang.String requestId;
    private java.lang.String system;
    private java.lang.String submissionId;
    private ru.tinkoff.bpm.topdsssigningprocess.model.sign.SigningSide signingSide;
    private java.lang.String inn;
    private java.lang.String snils;
    private java.util.List<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument> documents;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.requestId)) {
        this.requestId = data().deepCopy(fields()[0].schema(), other.requestId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.system)) {
        this.system = data().deepCopy(fields()[1].schema(), other.system);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.submissionId)) {
        this.submissionId = data().deepCopy(fields()[2].schema(), other.submissionId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.signingSide)) {
        this.signingSide = data().deepCopy(fields()[3].schema(), other.signingSide);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.inn)) {
        this.inn = data().deepCopy(fields()[4].schema(), other.inn);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.snils)) {
        this.snils = data().deepCopy(fields()[5].schema(), other.snils);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.documents)) {
        this.documents = data().deepCopy(fields()[6].schema(), other.documents);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing DocumentSignRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.requestId)) {
        this.requestId = data().deepCopy(fields()[0].schema(), other.requestId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.system)) {
        this.system = data().deepCopy(fields()[1].schema(), other.system);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.submissionId)) {
        this.submissionId = data().deepCopy(fields()[2].schema(), other.submissionId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.signingSide)) {
        this.signingSide = data().deepCopy(fields()[3].schema(), other.signingSide);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.inn)) {
        this.inn = data().deepCopy(fields()[4].schema(), other.inn);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.snils)) {
        this.snils = data().deepCopy(fields()[5].schema(), other.snils);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.documents)) {
        this.documents = data().deepCopy(fields()[6].schema(), other.documents);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'requestId' field.
      * @return The value.
      */
    public java.lang.String getRequestId() {
      return requestId;
    }


    /**
      * Sets the value of the 'requestId' field.
      * @param value The value of 'requestId'.
      * @return This builder.
      */
    public ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder setRequestId(java.lang.String value) {
      validate(fields()[0], value);
      this.requestId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'requestId' field has been set.
      * @return True if the 'requestId' field has been set, false otherwise.
      */
    public boolean hasRequestId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'requestId' field.
      * @return This builder.
      */
    public ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder clearRequestId() {
      requestId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'system' field.
      * @return The value.
      */
    public java.lang.String getSystem() {
      return system;
    }


    /**
      * Sets the value of the 'system' field.
      * @param value The value of 'system'.
      * @return This builder.
      */
    public ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder setSystem(java.lang.String value) {
      validate(fields()[1], value);
      this.system = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'system' field has been set.
      * @return True if the 'system' field has been set, false otherwise.
      */
    public boolean hasSystem() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'system' field.
      * @return This builder.
      */
    public ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder clearSystem() {
      system = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'submissionId' field.
      * @return The value.
      */
    public java.lang.String getSubmissionId() {
      return submissionId;
    }


    /**
      * Sets the value of the 'submissionId' field.
      * @param value The value of 'submissionId'.
      * @return This builder.
      */
    public ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder setSubmissionId(java.lang.String value) {
      validate(fields()[2], value);
      this.submissionId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'submissionId' field has been set.
      * @return True if the 'submissionId' field has been set, false otherwise.
      */
    public boolean hasSubmissionId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'submissionId' field.
      * @return This builder.
      */
    public ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder clearSubmissionId() {
      submissionId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'signingSide' field.
      * @return The value.
      */
    public ru.tinkoff.bpm.topdsssigningprocess.model.sign.SigningSide getSigningSide() {
      return signingSide;
    }


    /**
      * Sets the value of the 'signingSide' field.
      * @param value The value of 'signingSide'.
      * @return This builder.
      */
    public ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder setSigningSide(ru.tinkoff.bpm.topdsssigningprocess.model.sign.SigningSide value) {
      validate(fields()[3], value);
      this.signingSide = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'signingSide' field has been set.
      * @return True if the 'signingSide' field has been set, false otherwise.
      */
    public boolean hasSigningSide() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'signingSide' field.
      * @return This builder.
      */
    public ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder clearSigningSide() {
      signingSide = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'inn' field.
      * @return The value.
      */
    public java.lang.String getInn() {
      return inn;
    }


    /**
      * Sets the value of the 'inn' field.
      * @param value The value of 'inn'.
      * @return This builder.
      */
    public ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder setInn(java.lang.String value) {
      validate(fields()[4], value);
      this.inn = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'inn' field has been set.
      * @return True if the 'inn' field has been set, false otherwise.
      */
    public boolean hasInn() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'inn' field.
      * @return This builder.
      */
    public ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder clearInn() {
      inn = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'snils' field.
      * @return The value.
      */
    public java.lang.String getSnils() {
      return snils;
    }


    /**
      * Sets the value of the 'snils' field.
      * @param value The value of 'snils'.
      * @return This builder.
      */
    public ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder setSnils(java.lang.String value) {
      validate(fields()[5], value);
      this.snils = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'snils' field has been set.
      * @return True if the 'snils' field has been set, false otherwise.
      */
    public boolean hasSnils() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'snils' field.
      * @return This builder.
      */
    public ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder clearSnils() {
      snils = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'documents' field.
      * @return The value.
      */
    public java.util.List<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument> getDocuments() {
      return documents;
    }


    /**
      * Sets the value of the 'documents' field.
      * @param value The value of 'documents'.
      * @return This builder.
      */
    public ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder setDocuments(java.util.List<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument> value) {
      validate(fields()[6], value);
      this.documents = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'documents' field has been set.
      * @return True if the 'documents' field has been set, false otherwise.
      */
    public boolean hasDocuments() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'documents' field.
      * @return This builder.
      */
    public ru.tinkoff.bpm.topdsssigningprocess.model.sign.DocumentSignRequest.Builder clearDocuments() {
      documents = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DocumentSignRequest build() {
      try {
        DocumentSignRequest record = new DocumentSignRequest();
        record.requestId = fieldSetFlags()[0] ? this.requestId : (java.lang.String) defaultValue(fields()[0]);
        record.system = fieldSetFlags()[1] ? this.system : (java.lang.String) defaultValue(fields()[1]);
        record.submissionId = fieldSetFlags()[2] ? this.submissionId : (java.lang.String) defaultValue(fields()[2]);
        record.signingSide = fieldSetFlags()[3] ? this.signingSide : (ru.tinkoff.bpm.topdsssigningprocess.model.sign.SigningSide) defaultValue(fields()[3]);
        record.inn = fieldSetFlags()[4] ? this.inn : (java.lang.String) defaultValue(fields()[4]);
        record.snils = fieldSetFlags()[5] ? this.snils : (java.lang.String) defaultValue(fields()[5]);
        record.documents = fieldSetFlags()[6] ? this.documents : (java.util.List<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument>) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DocumentSignRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<DocumentSignRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DocumentSignRequest>
    READER$ = (org.apache.avro.io.DatumReader<DocumentSignRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.requestId);

    out.writeString(this.system);

    out.writeString(this.submissionId);

    out.writeEnum(this.signingSide.ordinal());

    if (this.inn == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.inn);
    }

    if (this.snils == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.snils);
    }

    long size0 = this.documents.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument e0: this.documents) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.requestId = in.readString();

      this.system = in.readString();

      this.submissionId = in.readString();

      this.signingSide = ru.tinkoff.bpm.topdsssigningprocess.model.sign.SigningSide.values()[in.readEnum()];

      if (in.readIndex() != 1) {
        in.readNull();
        this.inn = null;
      } else {
        this.inn = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.snils = null;
      } else {
        this.snils = in.readString();
      }

      long size0 = in.readArrayStart();
      java.util.List<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument> a0 = this.documents;
      if (a0 == null) {
        a0 = new SpecificData.Array<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument>((int)size0, SCHEMA$.getField("documents").schema());
        this.documents = a0;
      } else a0.clear();
      SpecificData.Array<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.requestId = in.readString();
          break;

        case 1:
          this.system = in.readString();
          break;

        case 2:
          this.submissionId = in.readString();
          break;

        case 3:
          this.signingSide = ru.tinkoff.bpm.topdsssigningprocess.model.sign.SigningSide.values()[in.readEnum()];
          break;

        case 4:
          if (in.readIndex() != 1) {
            in.readNull();
            this.inn = null;
          } else {
            this.inn = in.readString();
          }
          break;

        case 5:
          if (in.readIndex() != 1) {
            in.readNull();
            this.snils = null;
          } else {
            this.snils = in.readString();
          }
          break;

        case 6:
          long size0 = in.readArrayStart();
          java.util.List<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument> a0 = this.documents;
          if (a0 == null) {
            a0 = new SpecificData.Array<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument>((int)size0, SCHEMA$.getField("documents").schema());
            this.documents = a0;
          } else a0.clear();
          SpecificData.Array<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new ru.tinkoff.bpm.topdsssigningprocess.model.sign.RequestedDocument();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










