/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.tinkoff.bpm.topdsssigningprocess.model.sign;
@org.apache.avro.specific.AvroGenerated
public enum RequestedDocumentType implements org.apache.avro.generic.GenericEnumSymbol<RequestedDocumentType> {
  MORTGAGE_AGREEMENT, APPLICATION_FORM, INDIVIDUAL_CONDITIONS, CLIENT_APPLICATION_ROSREESTR, BANK_APPLICATION_ROSREESTR, CONTAINER_DESCRIPTION  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RequestedDocumentType\",\"namespace\":\"ru.tinkoff.bpm.topdsssigningprocess.model.sign\",\"symbols\":[\"MORTGAGE_AGREEMENT\",\"APPLICATION_FORM\",\"INDIVIDUAL_CONDITIONS\",\"CLIENT_APPLICATION_ROSREESTR\",\"BANK_APPLICATION_ROSREESTR\",\"CONTAINER_DESCRIPTION\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
