/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.tinkoff.bpm.topdsssigningprocess.model.sign;
@org.apache.avro.specific.AvroGenerated
public enum SigningSide implements org.apache.avro.generic.GenericEnumSymbol<SigningSide> {
  CLIENT, BANK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SigningSide\",\"namespace\":\"ru.tinkoff.bpm.topdsssigningprocess.model.sign\",\"symbols\":[\"CLIENT\",\"BANK\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
